
default:
  adapter: postgresql
  encoding: utf-8
  pool: 5
  username: dooxbsjcqrczro
  password: PNuvdV7nI0mYiR7NpYVQBSDUoB
  host: ec2-107-21-223-110.compute-1.amazonaws.com
  port: 5432
  database: d9nitp09it4gja

development:
  adapter: postgresql
  encoding: utf-8
  pool: 5
  username: dooxbsjcqrczro
  password: PNuvdV7nI0mYiR7NpYVQBSDUoB
  host: ec2-107-21-223-110.compute-1.amazonaws.com
  port: 5432
  database: d9nitp09it4gja