# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7afb3f7d502f771315b4ceceadb8f192fa91a7e5b535a345635aaeef142a3a5d410c5815a3f1a2223ad7662d36824faf2a0c17b7354093c6213f45362591f3fa

test:
  secret_key_base: 2b2d78ff646cf6ffd0d445db39910fc2551c304cdac9e02a0b54c5621d63daebe9774d762c9dcb3db19e55521d47edd3841635dc1f3e9a57ccaf491a5307f34a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
